# Exploring Pandas

In [1]:
import pandas as pd
iris=pd.read_csv('C:/Users/admin/Desktop/Sanlap files/iris.csv')#loading dataset

iris.shape #checking dataset dimension
iris.dtypes#checking data type
iris.loc[3:5] #allows to subset data using  index and labels
iris.iloc[3:4,3:5]
iris.to_csv('irisoutput.csv',index=False)#exporting dataframe as csv
pd.set_option('max rows',2)
pd.set_option('max columns',3) # number of rows or clumns that we want to see in the output
##Changing datatypes in pandas
planets=pd.read_csv("C:/Users/admin/Desktop/Sanlap files/planets.csv")
planets['number'][0].astype(int)# same line of cdoe is used to convert into str,float and int data
planets['year_dt']=pd.to_datetime(planets['year'],format='')#converion into datetime
#working with text data
names=pd.Series(['Red,Blue','Green;ellow'])
names=names.str.replace(';',',') #replacing unique value
names.str.len() #checking length
names.str.lower()# makes the whole string lowercase,similarly for uppercase
#working with dates
daterange=pd.period_range('1/1/2021',freq='30d',periods=4)#producing series of dates
df=pd.DataFrame(data=daterange,columns=['sample'])#converting into dataframe
df['date difference']=df['sample'].diff(periods=1) #finding howmuchthe dates are separated from the beginning
df['firstof the month']=df['sample'].values.astype('datetime64[M]') #finding first day of the month
df['sample']=df['sample'].dt.to_timestamp() # tranforming dates into proper datetime data type
df['sample'].dt.day_name() # transforming dates into days
#Managing null values
data.isna() #to check null values in data frame
data.dropna()#dropping null values by rows
data.dropna(axis=1) #dropping null values by columns
data.fillna(0)#fill the missing values
data.fillna(method='pad')
data.interpolate() #fills the missing values via injterpolation
#categorising
iris.groupby(['species']).max() #to groupby the dataframe according to various charecteristics
iris.groupby(['species']).agg({'sepal_length':['mean','max'],'sepal_width':'count'})#multiple aggregation methods to different variables
df=iris.groupby(['species']).get_group('setosa').head() # further filtering the grouped by data according to specific class
#Reshaping dataframes
#Pivot function
df = pd.DataFrame({'A': ['John', 'Josh', 'Mina'],
      'B': ['Masters', 'Masters', 'Graduate'],
      'C': [27, 23, 21]}) 
df.pivot('A', 'B', 'C')
#stack and melt function
df = pd.read_csv("")  
df_stacked = df.stack()
df_melt = df.melt(id_vars =['', '']) 
#merging datasets
data1.merge(data2,how='left',on='number')#left join
data1.merge(data2,how='inner',left_on='number',right_on='number') #innerjoin
data1.merge(data2,how='right',on='number',suffixes=('',"_right"))#rightjoin
data3=pd.concat([data1,data2]).reset_index(drop=True)#merging datasets
data4=pd.concat([data1,data2],axis=1) #concatenate dataframes horizontally
data.join(data1,rsuffix='_right')#join along index
#Mapping numerical data into several categories
df['']=pd.cut(df['numerical variable'],bins,labels=labels)#bins will the cut bvalues and lables will contain the names of those categories.
df['column']=pd.Categorical(df['column'],ordered=True,categories=labels)#transforms into categorical
df.sort_values(by=df['column'],ascending=True/False)#arranges the dataframecolumn
pd.get_dummies(df['column'])#transforms into dummy variablee
#plotting with pandas
data.plot()# time series data plot
data.plot.area(stack= False) #time series plot with area
iris.hist() #creates histogram
iris[['sepal_width','sepal_length']].plot.hist(alpha=0.5) #overlays the plots in same diagram
#Creating a scatter plot
colors={'versicolor':'red','setosa':'green','virginica':'blue'}
iris['colors']=iris['species'].map(colors)
iris.plot.scatter(x='sepal_width',y='sepal_length',color=iris['colors'])
#creating a pairplot
from pandas.plotting import scatter_matrix
scatter_matrix(iris,figsize=(15,9))
#Statistical functions
#measures of central tendency
iris.mean()
iris.median()
#measures of dispersion
iris.std()
iris.boxplot()
iris.describe()#data summary
iris.corr()#correlation matrix
iris.corr().style.bakground_gradient(cmap='RdYlGn',axis=None)
#Accelarating EDA
import pandas as pd
from pandas_profiling import ProfileReport
profile=ProfileReport(iris,'Iris Data Profile')  #Creates a summarised profile of the dataset
profile.to_notebook_iframe()
# DASK and SPARK(for big data) - Beyond pandas
import dask.dataframe as dd
df=dd.read_csv('C:/Users/admin/Desktop/Sanlap files/iris.csv') #importing data using dask
import databricks.koalas as ks
from pyuspark.sql import Sparksession
data1=ks.from_pandas(data) #transition of pandas dataframe to Koalas

OptionError: "No such keys(s): 'max rows'"

In [15]:

df_melt

               Name            Team variable      value
0     Avery Bradley  Boston Celtics   Number        0.0
1       Jae Crowder  Boston Celtics   Number       99.0
2      John Holland  Boston Celtics   Number       30.0
3       R.J. Hunter  Boston Celtics   Number       28.0
4     Jonas Jerebko  Boston Celtics   Number        8.0
...             ...             ...      ...        ...
3201   Shelvin Mack       Utah Jazz   Salary  2433333.0
3202      Raul Neto       Utah Jazz   Salary   900000.0
3203   Tibor Pleiss       Utah Jazz   Salary  2900000.0
3204    Jeff Withey       Utah Jazz   Salary   947276.0
3205            NaN             NaN   Salary        NaN

[3206 rows x 4 columns]